### ISSUE TITLE
Connect to different workspace in watson 

### ISSUE THREAD

**Issue by MazenSalama** [IBM/watson-google-assistant#14]
Hello
how could I link different workplace conversation in Watson to this code

Best Regards

**Comment by vperrinfr** [comment]
Hi,

What would be the trigger to switch from one workspace to another ?

Regards,

**Comment by markstur** [comment]
WORKSPACE_ID in your .env file (copy from env.sample) can be used to set your workspace.  The code will try to upload rental-car by default for convenience, but you can set the WORKSPACE_ID.

**Comment by markstur** [comment]
OK, I forgot this pattern is usually only deployed to the cloud w/o using the .env.  But still the code will use the env var WORKSPACE_ID.  In IBM Cloud you can set the runtime env to make that WORKSPACE_ID point to the workspace you like.
