### ISSUE TITLE
Sending multiple responses at a time

### ISSUE THREAD

**Issue by developer-bz** [IBM/watson-google-assistant#21]
Hi,

I want to send multiple responses to the user at a time using google assistant via watson assistant. Can you please guide me through this?

Thanks in advance

**Comment by markstur** [comment]
This is a simple single response app for now. Here's an example on stackoverflow if you want to try richer replies. 
https://stackoverflow.com/questions/45523479/how-to-send-multiple-statements-in-google-assistant-app
Google's docs are also pretty good:
https://developers.google.com/actions/assistant/responses#nodejs
