### ISSUE TITLE
Integration of own skill with google assistant.

### ISSUE THREAD

**Issue by SBTMentor** [IBM/watson-google-assistant#26]
Hi,

This code pattern worked well for me. Now when I built my own bot using watson assistant and try to integrate with google assistant, the response while testing in the simulator says '(display name) isn't responding right now. Try again soon'. I've exported JSON from the watson skills and also changed the URL to "https://gateway-lon.watsonplatform.net/assistant/api" (as created for my assistant) in actions.json. The gactions update and test commands didn't show any error.

What am I missing? Please help!

Best,

**Comment by markstur** [comment]
That is the URL for your assistant service, but you need to use the url for your deployed Node.js app.  Deploy to IBM Cloud with Cloud Foundry (or now OpenShift is an option) and put the app url in there.
